### ISSUE TITLE
Deletes frontmatter

### ISSUE THREAD

**Issue by mustafa0x** [StackExchange/Stacks-Editor#107]
Frontmatter support isn't probably a goal for this editor, but deleting text seems like a bug in any case.

**To Reproduce**
1. Toggle markdown on
2. Enter YAML frontmatter
3. Toggle markdown off
4. No frontmatter
5. Toggle markdown on, and frontmatter is gone

**Sample frontmatter**

```yaml
---
title: YAML Front Matter
description: A very simple way to add structured data to a page.
---
```
